# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_text',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mapper',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
